# Generated by Django 5.1.1 on 2024-09-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_post',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news_post',
            name='autor',
            field=models.TextField(null=True, verbose_name='Автор статьи'),
        ),
        migrations.AlterField(
            model_name='news_post',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news_post',
            name='short_description',
            field=models.CharField(max_length=200, null=True, verbose_name='Краткое описание новости'),
        ),
        migrations.AlterField(
            model_name='news_post',
            name='text',
            field=models.TextField(null=True, verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='news_post',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название новости'),
        ),
    ]
